############# Spanish navigation ##############

# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Nosotros"
url = "/about"
weight = 2

[[main]]
name = "Páginas"
weight = 3

[[main]]
parent = "Páginas"
name = "Blog"
url = "/blog"

[[main]]
parent = "Páginas"
name = "Contacto"
url = "/contact"

[[main]]
parent = "Páginas"
name = "Autores"
url = "/authors"

[[main]]
parent = "Páginas"
name = "Categorías"
url = "/categories"

[[main]]
parent = "Páginas"
name = "Página 404"
url = "/404"

# footer menu
[[footer]]
name = "Nosotros"
url = "/about"
weight = 1

[[footer]]
name = "Política de Privacidad"
url = "/privacy-policy"
weight = 2
