baseURL = 'https://paakto.com/'
locale = 'es-mx'
title = 'Paakto'
theme = 'hugoplate'
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false


############################# Build ##############################
[build]
[build.buildStats]
  enable = true
[[build.cachebusters]]
  source = 'assets/notwatching/hugo_stats\.json'
  target = 'css'

############################# Modules ############################
[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  disableWatch = true
  source = 'hugo_stats.json'
  target = 'assets/notwatching/hugo_stats.json'

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css" 
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css" 
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
lazy = false
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js" 
lazy = false
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true
[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true
[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false
[[params.plugins.js]]
link = "js/accordion.js"
lazy = true
[[params.plugins.js]] 
link = "js/tab.js"
lazy = true
[[params.plugins.js]]
link = "js/modal.js"
lazy = true
[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true

