[build]
  command = 'if [ "$CONTEXT" = "production" ]; then npm run build -- -b "$URL"; else npm run build -- -b "$DEPLOY_PRIME_URL"; fi'
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.162.1"
